# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'codeconvacr01-1931'
    repository: 'sample2'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '1'


- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'VerityStream-1308-Verity Production(caa88d8e-50da-4a07-9132-54b28d3060c7)'
    appType: 'webAppContainer'
    WebAppName: 'codeconv-priv-app03'
    deployToSlotOrASE: true
    ResourceGroupName: 'codeconv-rg01'
    SlotName: 'production'
    DockerNamespace: 'codeconvacr01.azurecr.io'
    DockerRepository: 'sample2'
    DockerImageTag: '1'